$(document).ready(function(){
    console.log('clickval start'); // 스크립트 연결 확인
    $("#time_1m").click(function(){
        $("#time_1m").val('');
    }
    )
    $("#time_5m").click(function(){
        $("#time_5m").val('');
    }
    )
    $("#time_10m").click(function(){
        $("#time_10m").val('');
    }
    )
    $("#time_15m").click(function(){
        $("#time_15m").val('');
    }
    )
    $("#time_30m").click(function(){
        $("#time_30m").val('');
    }
    )
    $("#time_60m").click(function(){
        $("#time_60m").val('');
    }
    )
    $("#time_3h").click(function(){
        $("#time_3h").val('');
    }
    )
    $("#time_8h").click(function(){
        $("#time_8h").val('');
    }
    )
    $("#time_12h").click(function(){
        $("#time_12h").val('');
    }
    )
    $("#time_24h").click(function(){
        $("#time_24h").val('');
    }
    )
    $("#time_3d").click(function(){
        $("#time_3d").val('');
    }
    )
    $("#time_7d").click(function(){
        $("#time_7d").val('');
    }
    )
    $("#time_30d").click(function(){
        $("#time_30d").val('');
    }
    )
$("#reset").on("click",function(){ // 초기화 버튼
    location.reload();
  });
});